# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

types = Type.create([{name: 'Anniversary', dropdown: 'occasion'}, {name: 'Birthday', dropdown: 'occasion'}, 
	{name: 'Just Because...', dropdown: 'occasion'}, {name: 'Thank you', dropdown: 'occasion'}, 
	{name: 'Love & Romance', dropdown: 'occasion'}, {name: 'Business Gifting', dropdown: 'occasion'}, 
	{name: 'Bonsai & Tropical Plants', dropdown: 'plant'}, {name: 'Flowering Plants', dropdown: 'plant'},
	{name: 'Green Plants', dropdown: 'plant'}, {name: 'Orchid & Exotic Plants', dropdown: 'plant'}, 
	{name: 'Seasonal Plants',  dropdown: 'plant'}, {name: 'Succulents', dropdown: 'plant'},
	{name: 'Daisies', dropdown: 'flower'}, {name: 'Iris', dropdown: 'flower'}, {name: 'Lilies', dropdown: 'flower'}, 
	{name: 'Roses', dropdown: 'flower'}, {name: 'Tulips', dropdown: 'flower'}, {name: 'Mixed Bouquets', dropdown: 'flower'}])

Flower.create([
	{name: 'Red Roses', 
		description: "If you're looking for an instant way to get your beloved to open her heart to you, send them 36 long-stemmed roses.", 
		price: 50, 
		quantity: 10, 
		types: [types[0], types[1], types[2], types[4], types[15]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Red_Roses.jpg")},
	{name: 'Rainbow Roses', 
		description: ' Imagine the overwhelming sense of abundance when your recipient opens the box to this splash of 24 roses in at least 4 different colors.', 
		price: 20, 
		quantity: 10,
		types: [types[0], types[2], types[3], types[4], types[5], types[15]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Rainbow_Roses.jpg")}, 
	{name: 'Bright Parisian Brunch', 
		description: "It’s the perfect way to energize and enhance your recipient’s mood as they start the day.", 
		price: 40, 
		quantity: 10,
		types: [types[0], types[15], types[17]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Bright_Parisian_Brunch.jpg")}, 
	{name: 'Purple Dendrobium Orchids', 
		description: "Wow somebody really, really loves you. Regal long-lasting 15 multiple bloom stems purple Dendrobium orchids: the perfect gift for an elegant person with upscale tastes.", 
		price: 45, 
		quantity: 10,
		types: [types[0]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Purple_Dendrobium_Orchids.jpg")},
	{name: 'Always & Forever', 
		description: "Fall in love all over again with this amazing bouquet of crisp 3 stems of white oriental lilies (2-4 blooms per stem) white lilies and 12 deep red tulips, as beautiful as the day you first met, is the perfect expression of love and devotion.", 
		price: 35, 
		quantity: 10,
		types: [types[0], types[2], types[4], types[14], types[16], types[17]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Always_&_Forever.jpg")}, 
	{name: 'Deluxe Hugs and Kisses', 
		description: "Our Deluxe Hugs and Kisses bouquet contains 20 ruby red tulips and 20 deep blue iris.", 
		price: 50, 
		quantity: 10,
		types: [types[0], types[1], types[2], types[4], types[13], types[16], types[17]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Deluxe_Hugs_and_Kisses.jpg")}, 
	{name: 'Pink Sapphire', 
		description: "Know someone who looks pretty in pink? Then send them Pink Sapphire, a \"powered by pink\" bouquet of 8 fresh cut pink roses, Peruvian lilies, asters and more.", 
		price: 30, 
		quantity: 10,
		types: [types[0], types[1], types[4], types[14], types[15], types[17]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Pink_Sapphire.jpg")}, 
	{name: 'Multi-Colored Tulips', 
		description: "Twenty tulips are a great way to make someone's day", 
		price: 28, 
		quantity: 10,
		types: [types[0], types[1], types[2], types[3], types[4], types[5], types[16]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Multi-Colored_Tulips.jpg")}, 
	{name: 'Smiles & Sunshine', 
	description: "Send a sunny splash of color and brighten their day with this vibrant bouquet of 10 Peruvian lilies, mixed with 6 multi-colored roses.", 
		price: 30, 
		quantity: 10,
		types: [types[0], types[2], types[3], types[4], types[14], types[15], types[17]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Smiles_&_Sunshine.jpg")}, 
	{name: 'Shower of Flowers', 
		description: "Pink and purple hues of daisy poms mixed with mini carnations, asters and alstroemeria make the perfect bouquet.", 
		price: 25, 
		quantity: 10,
		types: [types[0], types[1], types[2], types[3], types[4], types[5], types[12], types[17]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Shower_of_Flowers.jpg")}, 
	{name: 'Colorful Gerbera Daisies', 
		description: "Celebrate any occasion with a bright, beautiful Gerbera daisy bouquet of 15 stems Gerbera daisies (assorted colors).", 
		price: 50, 
		quantity: 10,
		types: [types[0], types[4], types[12]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Colorful_Gerbera_Daisies.jpg")}, 
	{name: 'White Roses', 
		description: "12 white roses are the ideal way to express purity.", 
		price: 30, 
		quantity: 10,
		types: [types[0], types[1], types[4], types[15]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/White_Roses.jpg")}, 
	{name: '100 Birthday Blooms',
		description: "Includes 100 blooms per bouquet, at least 17 stems of Peruvian lilies and 4-6 blooms per stem", 
		price: 50, 
		quantity: 10,
		types: [types[1], types[14]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/100_Birthday_Blooms.jpg")},
	{name: 'Birthday Sunflower Radiance',
		description: "Send 7 sunflowers and a little sunshine to brighten up someone's day!", 
		price: 35, 
		quantity: 10,
		types: [types[1], types[3]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Birthday_Sunflower_Radiance.jpg")},
	{name: 'Birthday Kaleidoscope',
		description: "Discover a kaleidoscope of gorgeous color - 9 purple lisianthus, 5 orange snapdragons, 3 magenta sweet william, 5 bicolor orange/red tulips, 3 purple snapdragons.", 
		price: 55, 
		quantity: 10,
		types: [types[1], types[1], types[17]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Birthday_Kaleidoscope.jpg")},
	{name: 'Happy Birthday Bouquet',
		description: "Pink roses, double lisianthus, yellow lilies, and green poms are all arranged with designer floral wrapping paper and ribbon in our Happy Birthday Bouquet", 
		price: 40, 
		quantity: 10,
		types: [types[1], types[14], types[15]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Happy_Birthday_Bouquet.jpg")},
	{name: 'Birthday Jubilee',
		description: "Pink Asiatic lilies and fresh cut blue iris will burst open and bloom right before your eyes.", 
		price: 30, 
		quantity: 10,
		types: [types[1], types[14]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Birthday_Jubilee.jpg")},
	{name: 'Stargazer Lilies',
		description: "Light up any special event with our premium bouquet of stargazer lilies, green hypericum and ruscus.", 
		price: 60, 
		quantity: 10,
		types: [types[2], types[4], types[14]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Stargazer_Lilies.jpg")},
	{name: 'Delightfully Dutch',
		description: "Inspired by European flower shops along cobblestone streets, this fresh arrangement of alstroemeria, blue thistle, pink riceflower and lavender trachelium will add vibrant European flair to any living space.", 
		price: 30, 
		quantity: 10,
		types: [types[2], types[3], types[17]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Delightfully_Dutch.jpg")},
	{name: 'Lavish Lavender',
		description: "Send a lovely bouquet of lavender roses, pom poms and fujis and they are sure to relish in this soothing blend of fresh spring blooms all day long.", 
		price: 30, 
		quantity: 10,
		types: [types[2], types[3], types[15], types[17]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Lavish_Lavender.jpg")},
	{name: '100 Blooms of Poms',
		description: "This is an assorted color collection of spring daisy poms.", 
		price: 55, 
		quantity: 10,
		types: [types[2], types[3], types[12]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/100_Blooms_of_Poms.jpg")},
	{name: '7 Stalks of Lucky Bamboo',
		description: "\"Bouquet\" of seven lucky bamboo stalks (dracaena sanderiana)", 
		price: 25, 
		quantity: 10,
		types: [types[2], types[3], types[6], types[8], types[10]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/7_Stalks_of_Lucky_Bamboo.jpg")},
	{name: 'Summer Festival',
		description: "From cheerleader to confidant, a mother is all things to everyone. Honor her and everything she does with this harmonious mix of tulips, lilies and snapdragon in a vibrant spring palette.", 
		price: 45, 
		quantity: 10,
		types: [types[3], types[14], types[17]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Summer_Festival.jpg")},
	{name: 'Carnival of Color',
		description: "A bouquet of outrageous beauty, our Carnival of Color Bouquet offers a playful collection of vibrant-toned flowers: orange lilies, burgundy asters, blue iris/purple asters, and so much more. A fun gift for a fun friend or anyone who's the life of the party.", 
		price: 55, 
		quantity: 10,
		types: [types[3], types[5], types[12], types[13], types[14], types[16], types[17]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Carnival_of_Color.jpg")},
	{name: 'Truly Spectacular',
		description: "Pink Asiatic lilies and fresh cut blue iris will burst open and bloom right before your eyes.", 
		price: 30, 
		quantity: 10,
		types: [types[3], types[13], types[14], types[17]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Truly_Spectacular.jpg")},
	{name: 'Serenity',
		description: "White snapdragons and roses mingle softly with green dianthus balls and viburnum. Help someone special unwind with this relaxing bouquet", 
		price: 60, 
		quantity: 10,
		types: [types[3], types[4], types[15], types[17]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Serenity.jpg")},
	{name: 'Potted Double Stem White Orchid',
		description: "Makes a great business, \“thank you\" gift, or a lovely addition to your home décor.", 
		price: 50, 
		quantity: 10,
		types: [types[3], types[6], types[7], types[9], types[10]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Potted_Double_Stem_White_Orchid.jpg")},
	{name: 'Potted Yellow Rose',
		description: "Looking for a floral gift that will keep someone happy for months? Choose this lovely miniature yellow rose bush with a standard woven basket.", 
		price: 40, 
		quantity: 10,
		types: [types[3], types[4], types[15]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Potted_Yellow_Rose.jpg")},
	{name: 'Joyful Bouquet',
		description: "This mixed bouquet is sure to impress! It is crafted from our ever popular Stargazer lilies and blue iris, and is a spectacular way to celebrate any occasion!", 
		price: 25, 
		quantity: 10,
		types: [types[3], types[5], types[13], types[14], types[17]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Joyful_Bouquet.jpg")},
	{name: 'Exotic Orchid Garden',
		description: "Enjoy the gorgeous combination of orange and purple in our Mardi Gras-inspired garden. Includes one purple phalaenopsis orchid and one orange guzmania bromeliad.",
		price: 55, 
		quantity: 10,
		types: [types[3], types[6], types[7], types[9]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Exotic_Orchid_Garden.jpg")},
	{name: 'Braided Money Tree',
		description: "A fixture of Feng Shui, the braided money tree is a perfect gift for a co-worker or for a friend.",
		price: 33, 
		quantity: 10,
		types: [types[3], types[5], types[6], types[8]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Braided_Money_Tree.jpg")},
	{name: 'Perfect Paradise',
		description: "There is nothing more beautiful than the vibrant colors of a tropical sunset - 4 heliconia psittacorum, 3 yellow maracas, 2 croton, 3 masangeana, 2 pandanus, 1 song of india, 3 red cordyline.", 
		price: 36, 
		quantity: 10,
		types: [types[3], types[4], types[17]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Perfect_Paradise.jpg")},
	{name: 'Honor Tree',
		description: "This tree is an honor to give and receive. Send it to someone for their birthday, in sympathy of a loss or just because.", 
		price: 26, 
		quantity: 10,
		types: [types[3], types[8]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Honor_Tree.jpg")},
	{name: 'Hot Pink Azalea',
		description: "Our beautiful dark pink azalea makes a stunning gift or addition to your home décor.", 
		price: 36, 
		quantity: 10,
		types: [types[3], types[7]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Hot_Pink_Azalea.jpg")},
	{name: 'Elegant Twist Bamboo',
		description: "Beautiful, elegant and easy to grow! Our \"twist\" bamboo plant is perfect for an office or any room of the house.", 
		price: 26, 
		quantity: 10,
		types: [types[3], types[6], types[8], types[10]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Elegant_Twist_Bamboo.jpg")},
	{name: 'Summer Flutters',
		description: "This cheerful trio includes one pink, one orange, and one yellow kalanchoe plant, each nestled in its own pastel tin pail. The three delicate butterfly clips add summery finishing touch, making this the perfect gift for a hostess, birthday girl, or even yourself!", 
		price: 36, 
		quantity: 10,
		types: [types[3], types[7], types[10]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Summer_Flutters.jpg")},
	{name: 'Lavish Roses',
		description: "Indulge someone you love with opulent blooms. This bouquet is overflowing with lush white and peach roses accented by lovely purple and pink spray stock and peach spray roses.", 
		price: 67, 
		quantity: 10,
		types: [types[4],types[15], types[17]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Lavish_Roses.jpg")},
	{name: 'Beauty & Grace',
		description: "Beauty & Grace is an amazing array of springtime florals, ready to make anyone smile. This dazzling bouquet will light up any room, setting the mood to one of happiness and joy.", 
		price: 57, 
		quantity: 10,
		types: [types[4], types[14], types[17]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Beauty_&_Grace.jpg")},
	{name: 'Peace on Earth Lily',
		description: "This handsome plant has white sail-like flowers that stand out between the shiny, dark green paddle-shaped leaves. The Spathiphyllum is a natural air purifier and does well indoors even in areas with little light.", 
		price: 48, 
		quantity: 10,
		types: [types[5], types[6], types[7], types[8], types[10]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Peace_on_Earth_Lily.jpg")},
	{name: 'Braided Money Tree Grove',
		description: "Enjoy a tiny forest of trees on your desk or indoor table, with our miniature braided money tree grove!", 
		price: 58, 
		quantity: 10,
		types: [types[5], types[6], types[8]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Braided_Money_Tree_Grove.jpg")},
	{name: 'Lush Tropical Evergreen',
		description: "This potted lily is a traditional gifting plant that's easy to care for and looks wonderful in any environment.", 
		price: 28, 
		quantity: 10,
		types: [types[5], types[6], types[7], types[8]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Lush_Tropical_Evergreen.jpg")},
	{name: 'Juniper Bonsai',
		description: "This is the perfect introduction to Bonsai, an art form that traces its roots to China.", 
		price: 31, 
		quantity: 10,
		types: [types[6], types[8]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Juniper–Bonsai.jpg")},
	{name: 'Fukien Tea Bonsai',
		description: "Exhibiting superior trunk movement our Fukien Tea Bonsai will add interest to any room. These easy to grow trees produce small white blooms in April and May, rewards for observant growers.", 
		price: 67, 
		quantity: 10,
		types: [types[6]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Fukien_Теа_Bonsai.jpg")},
	{name: 'Gensing Grafted Ficus Bonsai',
		description: "Our Ginseng Grafted Ficus is unique and unusual with thick exposed roots and thick-based trunk. Perfect for beginner enthusiasts and easy to grow. This tree will make a great indoor display. Should be kept indoors in order to protect it from direct sunlight. It can tolerate lower light conditions but will thrive with bright, indirect light.", 
		price: 49, 
		quantity: 10,
		types: [types[6], types[8]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Gensing_Grafted_Ficus_Bonsai.jpg")},
	{name: 'Chinese Elm Bonsai',
		description: "The undulating trunk and finely trained branches of this outdoor bonsai are sure to please. Chinese Elms are deciduous trees with small leaves that drop in winter.", 
		price: 49, 
		quantity: 10,
		types: [types[6]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Chinese_Elm_Bonsai.jpg")},
	{name: 'Tropical Bromeliad Garden',
		description: "A perfect gift or addition to your home or office décor! Includes three bromeliads, in merlot and orange colors.", 
		price: 56, 
		quantity: 10,
		types: [types[6], types[7], types[9]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Tropical_Bromeliad_Garden.jpg")},
	{name: 'Dwarf Mugo Pine Bonsai',
		description: "The hardy Dwarf Mugo Pine Bonsai can tolerate extremely cold winter conditions, making it a fine, low maintenance, outdoor choice.", 
		price: 46, 
		quantity: 10,
		types: [types[6], types[10]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Dwarf_Mugo_Pine_Bonsai.jpg")},
	{name: 'Deluxe Dancing Hearts Anthurium',
		description: "What better way to express your love than with a dazzling anthurium of vibrant red heart-shaped blooms and dark green heart-shaped leaves?", 
		price: 43, 
		quantity: 10,
		types: [types[6], types[7], types[9], types[10]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Deluxe_Dancing_Hearts_Anthurium.jpg")},
	{name: 'Giant Hanging Air Plant',
		description: "This beautiful, silvery air plant, which thrives on solely air and water, comes with a pretty pink macramé hanger to display anywhere in the home. This unique plant is an incredible conversation piece that makes for a fun and surprising gift, or a lovely addition to your own home.", 
		price: 23, 
		quantity: 10,
		types: [types[6], types[8], types[11]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Giant_Hanging_Air_Plant.jpg")},
	{name: 'Airplant Terrarium Globe with Macrame',
		description: "The delicate yet striking Tillandsia air plant with pink moss is the perfect choice for anyone! This air plant is extremely easy to care for, as it collects the nutrients it needs from the air around it, and its unique shape is perfectly showcased in an elegant glass globe with pink macramé. They will love finding the perfect place to hang it and show it off!", 
		price: 24, 
		quantity: 10,
		types: [types[6], types[9], types[10], types[11]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Airplant_Terrarium_Globe_with_Macrame.jpg")},
	{name: 'Remembrance Lily',
		description: "Our potted tropical heart plant arrives with bright white, heart-shaped blooms, and glossy green heart-shaped leaves. This is an easy-care plant for high-impact in a home or office setting! Care instructions are included.", 
		price: 43, 
		quantity: 10,
		types: [types[6], types[7]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Remembrance_Lily.jpg")},
	{name: 'Potted Azalea Topiary',
		description: "Elegant and gorgeous, our potted Azalea Topiary Tree is a beautiful gift or perfect addition to your home décor.", 
		price: 53, 
		quantity: 10,
		types: [types[7]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Potted_Azalea_Topiary.jpg")},
	{name: 'Potted Fragrant Gardenia',
		description: "Very popular plants, gardenias emit a delicate fragrance that captures the attention of all who pass. A fine addition to any decor and a thoughtful way to say, \"Thank You\", our potted Gardenia will not go unnoticed.", 
		price: 43, 
		quantity: 10,
		types: [types[7], types[10]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Potted_Fragrant_Gardenia.jpg")},
	{name: 'Potted Pink Rose',
		description: "Looking for a floral gift that will keep someone happy for months? Choose this lovely miniature pink rose bush with a standard woven basket.", 
		price: 36, 
		quantity: 10,
		types: [types[7], types[15]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Potted_Pink_Rose.jpg")},
	{name: 'Desert Jewel Succulent Garden',
		description: "Modern, lush and unique. This succulent garden can transform even an urban living space into a lush botanical sanctuary. It is the perfect gift for someone who appreciates something a little out of the ordinary and enjoys a low maintenance plant. An array of multi-colored succulents are planted for a truly eye catching gift.", 
		price: 43, 
		quantity: 10,
		types: [types[8], types[11]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Desert_Jewel_Succulent_Garden.jpg")},
	{name: 'Guardian Angel Tree',
		description: "Who couldn't use a Guardian Angel watching over them? Wrapped in burlap with a cream ribbon, this Cypress tree comes complete with a keepsake Guardian Angel ornament that gently reminds your special recipient that they have a designated angel always looking after them.", 
		price: 33, 
		quantity: 10,
		types: [types[8]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Guardian_Angel_Tree.jpg")},
	{name: 'Happy Heart Succulent Garden',
		description: "We’ve potted our succulent garden in a pink, heart shaped scalloped terra cotta pot for a modern way to tell someone you care! These unique succulents are the perfect gift because not only are they long lasting, but they’re incredibly low maintenance. Perfect for a sunny garden, doorstep, or patio table.", 
		price: 43, 
		quantity: 10,
		types: [types[8], types[11]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Happy_Heart_Succulent_Garden.jpg")},
	{name: 'Potted Double Stem Kaleidoscope Orchid',
		description: "Our double-stemmed kaleidoscope phalaenopsis orchid is breathtaking to behold. This variety is known for its mesmerizing creamy blooms with purple variegation.", 
		price: 47, 
		quantity: 10,
		types: [types[9], types[10]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Potted_Double_Stem_Kaleidoscope_Orchid.jpg")},
	{name: 'Potted Double Stem Painted Purple Orchid',
		description: "This purple-spotted stunner is sure to wow both the orchid aficionado and the orchid novice. The dark purple spots pop against the white petals making a sophisticated and showy display.", 
		price: 43, 
		quantity: 10,
		types: [types[9]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Potted_Double_Stem_Painted_Purple_Orchid.jpg")},
	{name: 'Rustic Succulent Trio',
		description: "These charming succulents in their wooden French trug box add a touch of rustic elegance to any windowsill or tabletop.", 
		price: 37, 
		quantity: 10,
		types: [types[11]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Rustic_Succulent_Trio.jpg")},
	{name: 'Sympathy Lilies',
		description: "These beautiful white Stargazer lilies are the ideal way to convey your condolences. Simple and elegant, this bouquet of fragrant white lilies fresh from the fields will gracefully express your sympathies.", 
		price: 43, 
		quantity: 10,
		types: [types[14]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Sympathy_Lilies.jpg")},
	{name: '100 Blooms of Peruvian Lilies',
		description: "This abundant bouquet of alstroemeria, known as Peruvian lilies, will add vibrant color to any room. This colorful bouquet contains 100 blooms of Peruvian Lilies, 4-6 blooms per stem.", 
		price: 21, 
		quantity: 10,
		types: [types[14]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/100_Blooms_of_Peruvian_Lilies.jpg")},
	{name: 'Peace and Prayers',
		description: "An appropriate and beautiful remembrance. Five pristine white roses stand out amongst eucalyptus and delicate green tricilium for a quiet serene bouquet. Sent with love, peace and prayers, this simple arrangement is the perfect way to express your deepest sympathies.", 
		price: 34, 
		quantity: 10,
		types: [types[15], types[17]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Peace_and_Prayers.jpg")},
	{name: '18 Pink Pearl Roses',
		description: "Lovely and luxurious, Pink Pearl Roses are the perfect gift for the Princess in your life. Fuller, fabulous, and long-lasting, this arrangement brings elegance and charm to any occasion.", 
		price: 44, 
		quantity: 10,
		types: [types[15]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/18_Pink_Pearl_Roses.jpg")},
	{name: '12 Pink Roses',
		description: "The most delicate of all roses, the pink rose combines refinement and grace few floral displays can match. This striking dozen subtly meshes several shades of pink. The sheer beauty of these pink roses will take their breath away. A perfect gift for a dear friend, or for a love in bloom.", 
		price: 34, 
		quantity: 10,
		types: [types[15]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/12_Pink_Roses.jpg")},
	{name: '18 Red Velvet Roses',
		description: "Discover the heartwarming dance of Red Velvet Roses. These one-of-a-kind roses in classic white and luscious red bring exquisite intrigue to any occasion.", 
		price: 37, 
		quantity: 10,
		types: [types[15]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/18_Red_Velvet_Roses.jpg")},
	{name: '12 Yellow Roses',
		description: "The yellow rose is perfect for expressing friendship and platonic love. Our long-stemmed yellow roses are also a great way to deliver sunshine into someone's life when they may need a little good cheer.", 
		price: 34, 
		quantity: 10,
		types: [types[15]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/12_Yellow_Roses.jpg")},
	{name: '12 Peach Roses',
		description: "Playful, elegant, dramatic: peach roses are perfect for most any occasion. And the long stems on these 12 peach roses only add to their beauty. Not sure what to get a lovely lady on her birthday? Looking for an impressive bouquet? Peach roses will get the job done gracefully.", 
		price: 34, 
		quantity: 10,
		types: [types[15]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/12_Peach_Roses.jpg")},
	{name: '12 Orange Roses',
		description: "The lush and vibrant orange hue of these fresh-cut roses is a perfect way to enjoy the summer season. A bouquet of Summer Roses adds a bright blast of color to any special occasion.", 
		price: 34, 
		quantity: 10,
		types: [types[15]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/12_Orange_Roses.jpg")},
	{name: 'Summer Showers',
		description: "Rain, rain, go away…so you can finally enjoy all the incredible summertime flowers! Nestled in adorable rain boots, this bouquet of 15 vibrant yellow tulips is the perfect gift for any springtime occasion.", 
		price: 49, 
		quantity: 10,
		types: [types[16]],
		flower_photo: File.new("#{Rails.root}/app/assets/images/Summer_Showers.jpg")}])